backend:
  name: git-gateway
  branch: main

media_folder: "images"         # Dossier où seront stockées les images dans ton repo
public_folder: "/images"       # Dossier public (dans l’URL)

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }



